### ISSUE TITLE
Update sonar.sh to fail if rhc port-forward fails

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue#11]
If you have multiple servers configured for openshift in rhc command the sonar.sh script should handle the case when you have the wrong server used for the port-forward.  Right now it fails to do the port forward but the builds continue but are not able to publish.  So unless you're paying attention you might not notice.

**Comment by luan-cestari** [comment]
Made a suggestion on https://github.com/lightblue-platform/lightblue/pull/20 . I think we could also evaluate the exit code returned from mvn
